// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLatency() {
  return window['go']['main']['App']['CheckLatency']();
}

export function DeleteCustomDNS(arg1) {
  return window['go']['main']['App']['DeleteCustomDNS'](arg1);
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCustomDNS() {
  return window['go']['main']['App']['GetCustomDNS']();
}

export function GetQueryStats() {
  return window['go']['main']['App']['GetQueryStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListCache() {
  return window['go']['main']['App']['ListCache']();
}

export function QueryCache(arg1) {
  return window['go']['main']['App']['QueryCache'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetCustomDNS(arg1, arg2) {
  return window['go']['main']['App']['SetCustomDNS'](arg1, arg2);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
