// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {upstream} from '../models';
import {cache} from '../models';
import {main} from '../models';
import {query} from '../models';

export function CheckLatency():Promise<Array<upstream.ServerLatency>>;

export function DeleteCustomDNS(arg1:string):Promise<void>;

export function GetCacheStats():Promise<cache.Stats>;

export function GetConfig():Promise<main.Config>;

export function GetCustomDNS():Promise<Array<main.CustomDNSEntry>>;

export function GetQueryStats():Promise<query.Stats>;

export function GetStatus():Promise<string>;

export function ListCache():Promise<Array<main.CacheEntryView>>;

export function QueryCache(arg1:string):Promise<Array<main.CacheEntryView>>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetCustomDNS(arg1:string,arg2:Array<string>):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
